name: Run Java Git Diff By Local

on:
  ##push事件：当向master-close分支推送代码时触发
  push:
    branches:
      - master-close
  ##pull_request事件：当向master-close分支发起或更新拉取请求时触发
  pull_request:
    branches:
      - master-close
##工作流
jobs:
  #定义了一个名为build-and-run的工作流作业，
  #runs-on: ubuntu-latest指定了该作业在Ubuntu最新版本的操作系统环境中运行。
  build-and-run:
    runs-on: ubuntu-latest

##步骤
    steps:
      #name: 步骤名称为"Checkout repository"
      #uses: 使用actions/checkout@v2官方动作来检出代码
      #fetch-depth: 2: 只检出最近的2个提交记录，用于后续比较当前提交(HEAD)和上一个提交(HEAD~1)的差异
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2  # 检出最后两个提交，以便可以比较 HEAD~1 和 HEAD

      #设置JDK 11环境：使用actions/setup-java@v2动作配置Java开发环境
      #指定Java发行版：选择Eclipse Temurin发行版（也可选用AdoptOpenJDK或Zulu等）
      #设置Java版本：配置使用Java 11版本
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'  # 你可以选择其他发行版，如 'adopt' 或 'zulu'
          java-version: '11'
      #编译Java代码
      #使用javac命令编译Java代码
      #运行Java代码
      - name: Run Java code
        run: |
          cd openai-code-review-sdk/src/main/java
          javac plus/gaga/middleware/sdk/OpenAiCodeReview.java
          java plus.gaga.middleware.sdk.OpenAiCodeReview
